# Generated by Django 3.2.1 on 2021-05-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('number_of_lectures', models.PositiveIntegerField()),
            ],
        ),
    ]
