# Generated by Django 3.2.1 on 2021-05-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210505_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='date_finish',
            new_name='date_end',
        ),
    ]
